export const CV_DUMMY_DATA = {
  personalInfo: {
    firstName: "John",
    lastName: "Doe",
    jobTitle: "Senior Software Engineer",
    email: "john.doe@gmail.com",
    phone: "+251 911 223344",
    city: "Addis Ababa",
    country: "Ethiopia",
    dateOfBirth: "1990-01-01",
    headline: "Seasoned software engineer with a passion for building scalable web applications and leading high-performing teams.",
    photo: "/images/dummy-profile.png",
    address: "Bole Sub-city, Woreda 03",
    website: "www.johndoe.dev",
    linkedin: "linkedin.com/in/johndoe",
  },
  summary: "Professional with 10+ years of experience in full-stack development. Proven track record of delivering high-quality software solutions and driving technical innovation. Expert in React, Node.js, and cloud architecture.",
  experience: [
    {
      id: "1",
      company: "Tech Solutions Inc.",
      jobTitle: "Senior Software Engineer",
      location: "Addis Ababa, Ethiopia",
      startDate: "2020-01-01",
      endDate: "Present",
      current: true,
      description: "Leading the development of a flagship cloud-based ERP system.",
      achievements: [
        "Reduced system latency by 40% through database optimization.",
        "Mentored 5 junior developers and improved team productivity by 25%.",
        "Implemented microservices architecture using Node.js and Docker.",
      ],
    },
    {
      id: "2",
      company: "Innovate Software",
      jobTitle: "Full Stack Developer",
      location: "Remote",
      startDate: "2017-06-01",
      endDate: "2019-12-31",
      current: false,
      description: "Developed and maintained multiple client-facing web applications.",
      achievements: [
        "Delivered 15+ high-impact projects on time and within budget.",
        "Integrated third-party payment gateways and improved checkout conversion by 15%.",
      ],
    },
  ],
  education: [
    {
      id: "1",
      school: "Addis Ababa University",
      degree: "Bachelor of Science in Computer Science",
      city: "Addis Ababa",
      startDate: "2013-09-01",
      endDate: "2017-07-01",
    },
  ],
  skills: [
    { id: "1", name: "React", level: "Expert" },
    { id: "2", name: "TypeScript", level: "Expert" },
    { id: "3", name: "Node.js", level: "Expert" },
    { id: "4", name: "PostgreSQL", level: "Advanced" },
    { id: "5", name: "Docker", level: "Intermediate" },
  ],
  languages: [
    { id: "1", language: "English", proficiency: "Native" },
    { id: "2", language: "Amharic", proficiency: "Native" },
  ],
  interests: ["Hiking", "Photography", "Open Source Contribution"],
  volunteer: [
    {
      id: "1",
      role: "Technical Mentor",
      organization: "Tech4All",
      description: "Teaching basic web development to high school students.",
    },
  ],
  coreCompetencies: [
    "Software Architecture",
    "Agile Methodology",
    "Cloud Computing",
    "Team Leadership",
    "Unit Testing",
  ],
};
