export const COMMON_SKILLS = [
  "Microsoft Office",
  "Customer Service",
  "Teamwork",
  "Communication",
  "Problem Solving",
  "Time Management",
  "Leadership",
  "Project Management",
  "Sales",
  "Data Entry",
  "Adaptability",
  "Creativity",
  "Critical Thinking",
  "Digital Literacy",
  "Interpersonal Skills",
  "Work Ethic",
  "Detail Oriented",
  "Analytical Skills",
  "Public Speaking",
  "Social Media Marketing",
];
